name: opinate_env
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python e Conda
  - python=3.10
  - pip
  
  # Data Science & Core
  - pandas
  - sqlalchemy
  - mysql-connector-python
  
  # Visualização e Dashboards
  - streamlit
  - plotly
  - matplotlib
  - wordcloud
  - networkx
  
  # Utilitários
  - python-dotenv
  - faker
  
  # Dependências exclusivas via PIP (PyPI)
  - pip:
      - google-genai